#[===============================================[/*
This is part of the TWX build and test system.
https://github.com/TeXworks/texworks
(C)  JL 2023
*/
/** @file
  * @brief TwxAssertLib test suite.
  *
  * First test.
  *//*
#]===============================================]

include_guard ( GLOBAL )

twx_test_suite_will_begin ()
block ()

twx_test_unit_will_begin ( NAME "twx_assert_undefined" )
if ( TWX_TEST_UNIT_RUN )
  block ()
  twx_fatal_test ()
  unset ( dummy )
  twx_assert_undefined ( dummy )
  twx_fatal_catched ( IN_VAR v )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  set ( dummy "" )
  twx_assert_undefined ( dummy )
  twx_fatal_assert_failed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

twx_test_unit_will_begin ( NAME "twx_assert_defined" ID defined )
if ( TWX_TEST_UNIT_RUN )
  block ()
  twx_fatal_test ()
  set ( dummy "" )
  twx_assert_defined ( dummy )
  twx_fatal_catched ( IN_VAR v )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  unset ( dummy )
  twx_assert_defined ( dummy )
  twx_fatal_assert_failed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

twx_test_unit_will_begin ( NAME "twx_assert_compare(yes)" ID compare_yes )
if ( TWX_TEST_UNIT_RUN )
  block ()
  twx_fatal_test ()
  twx_assert_compare ( 1 < 2 )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_compare ( 1 <= 2 )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_compare ( 2 <= 2 )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_compare ( 2 == 2 )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_compare ( 2 = 2 )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_compare ( 2 >= 2 )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_compare ( 3 >= 2 )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_compare ( 3 > 2 )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_compare ( 3 <> 2 )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_compare ( 3 != 2 )
  twx_fatal_assert_passed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

twx_test_unit_will_begin ( NAME "twx_assert_compare(no)" ID compare_no )
if ( TWX_TEST_UNIT_RUN )
  block ()
  twx_fatal_test ()
  twx_assert_compare ( 3 < 2 )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  twx_assert_compare ( 3 <= 2 )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  twx_assert_compare ( 3 == 2 )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  twx_assert_compare ( 3 = 2 )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  twx_assert_compare ( 2 >= 3 )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  twx_assert_compare ( 2 > 3 )
  twx_fatal_assert_failed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

twx_test_unit_will_begin ( NAME "twx_assert_compare(pipe/yes)" ID compare_pipe_yes )
if ( TWX_TEST_UNIT_RUN )
  block ()
  twx_fatal_test ()
  twx_assert_compare ( 1 < 2 < 3 )
  twx_fatal_catched ( IN_VAR v )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_compare ( 1 < 2 > 1 )
  twx_fatal_catched ( IN_VAR v )
  twx_fatal_assert_passed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

twx_test_unit_will_begin ( NAME "twx_assert_compare(pipe/no)" ID compare_pipe_no )
if ( TWX_TEST_UNIT_RUN )
  block ()
  twx_fatal_test ()
  twx_assert_compare ( 3 < 2 < 3 )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  twx_assert_compare ( 1 < 2 < 1 )
  twx_fatal_assert_failed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

twx_test_unit_will_begin ( NAME "twx_assert_non_void" ID non_void )
if ( TWX_TEST_UNIT_RUN )
  block ()
  twx_fatal_test ()
  set ( foo bar )
  twx_assert_non_void ( foo )
  twx_fatal_catched ( IN_VAR v )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  set ( foo bar )
  set ( bar baz )
  twx_assert_non_void ( foo bar )
  twx_fatal_catched ( IN_VAR v )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  unset ( foo )
  unset ( bar )
  twx_assert_non_void ( foo )
  twx_fatal_catched ( IN_VAR v )
  if ( v STREQUAL "" )
    message ( STATUS FATAL_ERROR "FAILURE" )
  endif ()
  twx_fatal_test ()
  set ( foo )
  twx_assert_non_void ( foo )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  unset ( foo )
  set ( bar baz )
  twx_assert_non_void ( foo bar )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  unset ( foo )
  set ( bar baz )
  twx_assert_non_void ( bar foo )
  twx_fatal_assert_failed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

twx_test_unit_will_begin ( NAME "twx_assert_0" ID 0 )
if ( TWX_TEST_UNIT_RUN )
  block ()
  twx_fatal_test ()
  set ( foo )
  twx_assert_0 ( "${foo}" )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  set ( foo )
  set ( bar 0 )
  twx_assert_0 ( "${foo}" "${bar}" )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  set ( foo )
  set ( bar 0 )
  twx_assert_0 ( "${bar}" "${foo}" )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  set ( foo "0" )
  twx_assert_0 ( "${foo}" )
  twx_fatal_catched ( IN_VAR v )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  set ( foo "wizz" )
  twx_assert_0 ( "${foo}" )
  twx_fatal_assert_failed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

twx_test_unit_will_begin ( NAME "twx_assert_true/twx_assert_false" ID true_false )
if ( TWX_TEST_UNIT_RUN )
  block ()
  set ( foo ON )
  twx_fatal_test ()
  twx_assert_true ( "foo" )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_true ( "${foo}" )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_false ( "foo" )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  twx_assert_false ( "${foo}" )
  twx_fatal_assert_failed ()

  set ( foo OFF )
  twx_fatal_test ()
  twx_assert_false ( "foo" )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_false ( "${foo}" )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_true ( "foo" )
  twx_fatal_assert_failed ()
  twx_fatal_test ()
  twx_assert_true ( "${foo}" )
  twx_fatal_assert_failed ()

  set ( foo ON )
  set ( bar ON )
  twx_assert_true ( "foo" "bar" "${foo}" "${bar}" )
  
  set ( foo )
  twx_assert_false ( foo "foo" )

  twx_assert_true ( "" )

  if ( "" )
    message ( STATUS "VOID IS TRUE" )
  endif ()
  
  if ( NOT "" )
    message ( STATUS "VOID IS FALSE" )
  endif ()
  
  if ( NOT ( NOT "" ) )
    message ( STATUS "VOID IS TRUE" )
  endif ()

  set ( foo )
  if ( foo )
    message ( STATUS "UNDEFINED IS TRUE" )
  endif ()
  if ( NOT foo )
    message ( STATUS "UNDEFINED IS FALSE" )
  endif ()
  twx_assert_false ( foo )

  twx_fatal_test ()
  set ( foo "ON" )
  twx_assert_true ( "${foo}" )
  twx_fatal_assert_passed ()

  twx_fatal_test ()
  unset ( wizz )
  set ( foo "wizz" )
  twx_assert_false ( "wizz" )
  twx_fatal_assert_passed ()
  twx_assert_true ( "foo" )
  twx_fatal_assert_passed ()
  
  twx_fatal_test ()
  set ( foo N )
  twx_assert_false ( foo )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  set ( foo N )
  twx_assert_true ( foo )
  twx_fatal_assert_failed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

twx_test_unit_will_begin ( NAME "twx_assert_exists" ID exists )
if ( TWX_TEST_UNIT_RUN )
  block ()
  twx_fatal_test ()
  twx_assert_exists ( "${CMAKE_CURRENT_LIST_DIR}/" )
  twx_fatal_assert_passed ()
  twx_fatal_test ()
  twx_assert_exists ( "${CMAKE_CURRENT_LIST_DIR}/NO_FILE_AT_THIS_PATH" )
  twx_fatal_assert_failed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

twx_test_unit_will_begin ( NAME "twx_assert_target" )
if ( TWX_TEST_UNIT_RUN AND NOT TARGET TwxAssertTest.cmakeDummyTarget )
  block ()
  twx_assert_target ( "TwxAssertTest.cmakeDummyTarget" )
  twx_fatal_catched ( IN_VAR v )
  if ( v STREQUAL "" )
    message ( FATAL_ERROR "FAILURE" )
  endif ()
  add_custom_target ( "TwxAssertTest.cmakeDummyTarget" )
  twx_fatal_test ()
  twx_assert_target ( "TwxAssertTest.cmakeDummyTarget" )
  twx_fatal_assert_passed ()
  endblock ()
endif ()
twx_test_unit_did_end ()

endblock ()
twx_test_suite_did_end ()

#*/
