#[===============================================[/*
This is part of the TWX build and test system.
https://github.com/TeXworks/texworks
(C)  JL 2023
*/
/** @file
  * @brief Testing Expect.
  *
  * First test.
  *//*
#]===============================================]

include_guard ( GLOBAL )

message ( STATUS "TwxExpectLib test...")

include ( "${CMAKE_CURRENT_LIST_DIR}/../../TwxExpectLib.cmake" )

include ( "${CMAKE_CURRENT_LIST_DIR}/../TwxCore/TwxCoreTest.cmake" )

block ()
twx_test_suite_will_begin ()

message ( STATUS "twx_expect_equal_string" )
block ()
list ( APPEND CMAKE_MESSAGE_CONTEXT equal_string )
twx_test_fatal_assert_passed ()
if ( TRUE )
  twx_test_fatal ()
  twx_expect_equal_string ( "" "" )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  twx_expect_equal_string ( "ABC" "ABC" )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  set ( DEF "ABC" )
  twx_expect_equal_string ( "ABC" "DEF" )
  twx_test_fatal_assert_failed ()
endif ()
twx_test_fatal ()
endblock ()

message ( STATUS "twx_expect_unequal_string" )
block ()
list ( APPEND CMAKE_MESSAGE_CONTEXT unequal_string )
twx_test_fatal_assert_passed ()
if ( TRUE )
  twx_test_fatal ()
  twx_expect_unequal_string ( "" "" )
  twx_test_fatal_assert_failed ()
  twx_test_fatal ()
  twx_expect_unequal_string ( "ABC" "ABC" )
  twx_test_fatal_assert_failed ()
  twx_test_fatal ()
  set ( DEF "ABC" )
  twx_expect_unequal_string ( "ABC" "DEF" )
  twx_test_fatal_assert_passed ()
endif ()
twx_test_fatal ()
endblock ()

message ( STATUS "twx_expect_equal_number" )
block ()
list ( APPEND CMAKE_MESSAGE_CONTEXT equal_number )
twx_test_fatal_assert_passed ()
if ( TRUE )
  twx_test_fatal ()
  twx_expect_equal_number ( 4 4 )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  twx_expect_equal_number ( 4 0x4 )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  set ( 0x4 5 )
  twx_expect_equal_number ( 4 0x4 )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  if ( "4" EQUAL "0x44" )
    message ( FATAL_ERROR "FAILED" )
  endif ()
  twx_expect_equal_number ( 4 0x44 )
  twx_test_fatal_assert_failed ()
  twx_test_fatal ()
  set ( 0x44 4 )
  twx_expect_equal_number ( 4 0x44 )
  twx_test_fatal_assert_failed ()
endif ()
twx_test_fatal ()
endblock ()

message ( STATUS "twx_expect_unequal_number" )
block ()
list ( APPEND CMAKE_MESSAGE_CONTEXT unequal_number )
twx_test_fatal_assert_passed ()
if ( TRUE )
  twx_test_fatal ()
  set ( 0x4 5 )
  twx_expect_unequal_number ( 4 0x4 )
  twx_test_fatal_assert_failed ()
  twx_test_fatal ()
  set ( 0x44 4 )
  twx_expect_unequal_number ( 4 0x44 )
  twx_test_fatal_assert_passed ()
endif ()
twx_test_fatal ()
endblock ()

message ( STATUS "twx_expect" )
block ()
list ( APPEND CMAKE_MESSAGE_CONTEXT expect )
twx_test_fatal_assert_passed ()
if ( TRUE )
  twx_test_fatal ()
  set ( ABC DEF )
  twx_expect ( ABC DEF )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  set ( ABC )
  twx_expect ( ABC DEF )
  twx_test_fatal_assert_failed ()
  twx_test_fatal ()
  set ( ABC )
  set ( DEF ABC )
  twx_expect ( ABC DEF )
  twx_test_fatal_assert_failed ()
  twx_test_fatal ()
  set ( ABC 4 )
  twx_expect ( ABC 0x4 )
  twx_test_fatal_assert_failed ()
  twx_test_fatal ()
  set ( ABC 4 )
  twx_expect ( ABC 0x4 NUMBER )
  twx_test_fatal_assert_passed ()
endif ()
twx_test_fatal ()
endblock ()

message ( STATUS "twx_unexpect" )
block ()
list ( APPEND CMAKE_MESSAGE_CONTEXT unexpect )
twx_test_fatal_assert_passed ()
if ( TRUE )
  unset ( ABC )
  unset ( DEF )
  twx_test_fatal ()
  set ( ABC ABC )
  twx_unexpect ( ABC DEF )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  set ( ABC DEF )
  twx_unexpect ( ABC DEF )
  twx_test_fatal_assert_failed ()
  twx_test_fatal ()
  set ( ABC ABC )
  set ( DEF ABC )
  twx_unexpect ( ABC DEF )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  set ( ABC DEF )
  set ( DEF ABC )
  twx_unexpect ( ABC DEF )
  twx_test_fatal_assert_failed ()
  unset ( DEF )
  twx_test_fatal ()
  set ( ABC ABC )
  twx_unexpect ( ABC ABC )
  twx_test_fatal_assert_failed ()
  twx_test_fatal ()
  set ( ABC DEF )
  twx_unexpect ( ABC ABC )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  set ( ABC DEF )
  set ( DEF ABC )
  twx_unexpect ( ABC ABC )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  set ( ABC 4 )
  twx_unexpect ( ABC 0x4 )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  set ( ABC 4 )
  twx_unexpect ( ABC 0x4 NUMBER )
  twx_test_fatal_assert_failed ()
endif ()
twx_test_fatal ()
endblock ()

message ( STATUS "twx_expect_matches" )
block ()
list ( APPEND CMAKE_MESSAGE_CONTEXT matches )
twx_test_fatal_assert_passed ()
if ( TRUE )
  twx_test_fatal ()
  twx_expect_matches ( "ABC" "^...$" )
  twx_test_fatal_assert_passed ()
  twx_test_fatal ()
  twx_expect_matches ( "ABC" "^..$" )
  twx_test_fatal_assert_failed ()
endif ()
twx_test_fatal ()
endblock ()

message ( STATUS "twx_expect_unmatches" )
block ()
list ( APPEND CMAKE_MESSAGE_CONTEXT unmatches )
twx_test_fatal_assert_passed ()
if ( TRUE )
  twx_test_fatal ()
  twx_expect_unmatches ( "ABC" "^...$" )
  twx_test_fatal_assert_failed ()
  twx_test_fatal ()
  twx_expect_unmatches ( "ABC" "^..$" )
  twx_test_fatal_assert_passed ()
endif ()
twx_test_fatal ()
endblock ()

twx_test_suite_did_end ()
endblock ()

message ( STATUS "TwxExpectLib test...")

#*/
