#[===============================================[/*
This is part of the TWX build and test system.
https://github.com/TeXworks/texworks
(C)  JL 2023
*/
/** @file
  * @brief Testing Expect.
  *
  * First test.
  *//*
#]===============================================]

include_guard ( GLOBAL )

twx_test_suite_push ()
block ()

# ANCHOR: equal_string
twx_test_unit_push ( CORE equal_string )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "``''==``''" )
  twx_expect_equal_string ( "" "" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "``ABC''==``ABC''" )
  twx_expect_equal_string ( "ABC" "ABC" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "``ABC''==``DEF''" )
  twx_expect_equal_string ( "ABC" "DEF" )
  twx_test_simple_fail ()
  twx_test_simple_check ( "``ABC''==``DEF''" )
  set ( DEF "ABC" )
  twx_expect_equal_string ( "ABC" "DEF" )
  twx_test_simple_fail ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: unequal_string
twx_test_unit_push ( CORE unequal_string )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "``''!=``''" )
  twx_expect_unequal_string ( "" "" )
  twx_test_simple_fail ()
  twx_test_simple_check ( "``ABC''!=``ABC''" )
  twx_expect_unequal_string ( "" "" )
  twx_test_simple_fail ()
  twx_test_simple_check ( "``ABC''!=``DEF''" )
  twx_expect_unequal_string ( "ABC" "DEF" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "``ABC''!=``DEF''" )
  set ( ABC DEF )
  twx_expect_unequal_string ( "ABC" "DEF" )
  twx_test_simple_pass ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: equal_number
twx_test_unit_push ( CORE equal_number )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "4==4" )
  twx_expect_equal_number ( 4 4 )
  twx_test_simple_pass ()
  twx_test_simple_check ( "4==0x4" )
  twx_expect_equal_number ( 4 0x4 )
  twx_test_simple_pass ()
  twx_test_simple_check ( "4==0x4(2)" )
  set ( 0x4 5 )
  twx_expect_equal_number ( 4 0x4 )
  twx_test_simple_pass ()
  twx_test_simple_check ( "4==0x44" )
  twx_expect_equal_number ( 4 0x44 )
  twx_test_simple_fail ()
  twx_test_simple_check ( "0x44==4" )
  twx_expect_equal_number ( 0x44 4 )
  twx_test_simple_fail ()
  twx_test_simple_check ( "0x44==4(2)" )
  set ( 0x44 4 )
  twx_expect_equal_number ( 0x44 4 )
  twx_test_simple_fail ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: unequal_number
twx_test_unit_push ( CORE unequal_number )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "4!=4" )
  twx_expect_unequal_number ( 4 4 )
  twx_test_simple_fail ()
  twx_test_simple_check ( "4!=5" )
  twx_expect_unequal_number ( 4 5 )
  twx_test_simple_pass ()
  twx_test_simple_check ( "4!=0x4" )
  twx_expect_unequal_number ( 4 0x4 )
  twx_test_simple_fail ()
  twx_test_simple_check ( "4!=0x4(<=5)" )
  set ( 0x4 5 )
  twx_expect_unequal_number ( 4 0x4 )
  twx_test_simple_fail ()
  twx_test_simple_check ( "4!=0x44" )
  set ( 0x44 4 )
  twx_expect_unequal_number ( 4 0x44 )
  twx_test_simple_pass ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: expect
twx_test_unit_push ( NAME "twx_expect" CORE expect )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "ABC(<=DEF)==DEF" )
  set ( ABC DEF )
  twx_expect ( ABC DEF )
  twx_test_simple_pass ()
  twx_test_simple_check ( "ABC(UNDEFINED)==DEF" )
  set ( ABC )
  twx_expect ( ABC DEF )
  twx_test_simple_fail ()
  twx_test_simple_check ( "ABC(UNDEFINED)==DEF(<=ABC)" )
  set ( ABC )
  set ( DEF ABC )
  twx_expect ( ABC DEF )
  twx_test_simple_fail ()
  twx_test_simple_check ( "ABC(<=4)==0x4" )
  set ( ABC 4 )
  twx_expect ( ABC 0x4 )
  twx_test_simple_fail ()
  twx_test_simple_check ( "NUMBER: ABC(<=4)==0x4" )
  set ( ABC 4 )
  twx_expect ( ABC 0x4 NUMBER )
  twx_test_simple_pass ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: unexpect
twx_test_unit_push ( NAME "twx_unexpect" CORE unexpect )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "ABC(<=ABC)!=DEF(UNDEFINED)" )
  set ( ABC ABC )
  set ( DEF )
  twx_unexpect ( ABC DEF )
  twx_test_simple_pass ()
  twx_test_simple_check ( "ABC(<=DEF)!=DEF(UNDEFINED)" )
  set ( ABC DEF )
  set ( DEF )
  twx_unexpect ( ABC DEF )
  twx_test_simple_fail ()
  twx_test_simple_check ( "ABC(<=ABC)!=DEF(<=ABC)" )
  set ( ABC ABC )
  set ( DEF ABC )
  twx_unexpect ( ABC DEF )
  twx_test_simple_pass ()
  twx_test_simple_check ( "ABC(<=DEF)!=DEF(<=ABC)" )
  set ( ABC DEF )
  set ( DEF ABC )
  twx_unexpect ( ABC DEF )
  twx_test_simple_fail ()
  twx_test_simple_check ( "ABC(<=ABC)!=ABC" )
  set ( ABC ABC )
  twx_unexpect ( ABC ABC )
  twx_test_simple_fail ()
  twx_test_simple_check ( "ABC(<=DEF)!=ABC" )
  set ( ABC DEF )
  twx_unexpect ( ABC ABC )
  twx_test_simple_pass ()
  twx_test_simple_check ( "ABC(<=4)!=0x4" )
  set ( ABC 4 )
  twx_unexpect ( ABC 0x4 )
  twx_test_simple_pass ()
  twx_test_simple_check ( "NUMBER: ABC(<=4)!=0x4" )
  set ( ABC 4 )
  twx_unexpect ( ABC 0x4 NUMBER )
  twx_test_simple_fail ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: matches
twx_test_unit_push ( CORE matches )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "``ABC'' MATCHES ``^...$''" )
  twx_expect_matches ( "ABC" "^...$" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "``ABC'' MATCHES ``^..$''" )
  twx_expect_matches ( "ABC" "^..$" )
  twx_test_simple_fail ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: unmatches
twx_test_unit_push ( CORE unmatches )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "``ABC'' UNMATCHES ``^...$''" )
  twx_expect_unmatches ( "ABC" "^...$" )
  twx_test_simple_fail ()
  twx_test_simple_check ( "``ABC'' UNMATCHES ``^..$''" )
  twx_expect_unmatches ( "ABC" "^..$" )
  twx_test_simple_pass ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: newline
twx_test_unit_push ( CORE newline )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "``\nZERO'' MATCHES ``ZERO''" )
  twx_expect_matches ( "\nZERO" "ZERO" )
  twx_test_simple_pass ()
  endblock ()
endif ()
twx_test_unit_pop ()

endblock ()
twx_test_suite_pop ()

#*/
