#[===============================================[/*
This is part of the TWX build and test system.
https://github.com/TeXworks/texworks
(C)  JL 2023
*/
/** @file
  * @brief TwxAssertLib test suite.
  *
  * First test.
  *//*
#]===============================================]

include_guard ( GLOBAL )

twx_test_suite_push ()
block ()

# ANCHOR: undefined
twx_test_unit_push ( CORE "undefined" )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "Undefined dummy" )
  unset ( dummy )
  twx_test_simple_pass ()
  twx_test_simple_check ( "Defined dummy" )
  set ( dummy "" )
  twx_assert_undefined ( dummy )
  twx_test_simple_fail ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: defined
twx_test_unit_push ( CORE "defined" )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "Defined dummy" )
  set ( dummy "" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "Undefined dummy" )
  unset ( dummy )
  twx_assert_defined ( dummy )
  twx_test_simple_fail ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: compare_yes
twx_test_unit_push ( NAME "twx_assert_compare(yes)" CORE compare_yes )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  macro ( twx_test_one_shot )
    string ( REPLACE ";" " " twx_test_one_shot.v "${ARGV}" )
    twx_test_simple_check ( "Assert ${twx_test_one_shot.v}" )
    twx_assert_compare ( ${ARGV} )
    twx_test_simple_pass ()
  endmacro ()
  twx_test_one_shot ( 1 < 2 )
  twx_test_one_shot ( 1 <= 2 )
  twx_test_one_shot ( 2 <= 2 )
  twx_test_one_shot ( 2 == 2 )
  twx_test_one_shot ( 2 = 2 )
  twx_test_one_shot ( 2 >= 2 )
  twx_test_one_shot ( 3 >= 2 )
  twx_test_one_shot ( 3 > 2 )
  twx_test_one_shot ( 3 <> 2 )
  twx_test_one_shot ( 3 != 2 )
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: compare_no
twx_test_unit_push ( NAME "twx_assert_compare(no)" CORE compare_no )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  macro ( twx_test_one_shot )
    string ( REPLACE ";" " " twx_test_one_shot.v "${ARGV}" )
    twx_test_simple_check ( "Assert ! ${twx_test_one_shot.v}" )
    twx_assert_compare ( ${ARGV} )
    twx_test_simple_fail ()
  endmacro ()
  twx_test_one_shot ( 3 < 2 )
  twx_test_one_shot ( 3 <= 2 )
  twx_test_one_shot ( 3 == 2 )
  twx_test_one_shot ( 3 = 2 )
  twx_test_one_shot ( 2 >= 3 )
  twx_test_one_shot ( 2 > 3 )
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: compare_pipe_yes
twx_test_unit_push ( NAME "twx_assert_compare(pipe/yes)" CORE compare_pipe_yes )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  macro ( twx_test_one_shot )
    string ( REPLACE ";" " " twx_test_one_shot.v "${ARGV}" )
    twx_test_simple_check ( "Assert ${twx_test_one_shot.v}" )
    twx_assert_compare ( ${ARGV} )
    twx_test_simple_pass ()
  endmacro ()
  twx_test_one_shot ( 1 < 2 < 3 )
  twx_test_one_shot ( 1 < 2 > 1 )
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: compare_pipe_no
twx_test_unit_push ( NAME "twx_assert_compare(pipe/no)" CORE compare_pipe_no )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  macro ( twx_test_one_shot )
    string ( REPLACE ";" " " twx_test_one_shot.v "${ARGV}" )
    twx_test_simple_check ( "Assert ! ${twx_test_one_shot.v}" )
    twx_assert_compare ( ${ARGV} )
    twx_test_simple_fail ()
  endmacro ()
  twx_test_one_shot ( 3 < 2 < 3 )
  twx_test_one_shot ( 1 < 2 < 1 )
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: non_void
twx_test_unit_push ( CORE "non_void" )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "foo => bar" )
  set ( foo bar )
  twx_assert_non_void ( foo )
  twx_test_simple_pass ()
  twx_test_simple_check ( "foo => bar, bar => baz" )
  set ( foo bar )
  set ( bar baz )
  twx_assert_non_void ( foo bar )
  twx_test_simple_pass ()
  twx_test_simple_check ( "foo => UNDEFINED" )
  set ( foo )
  twx_assert_non_void ( foo )
  twx_test_simple_fail ()
  twx_test_simple_check ( "foo => bar, bar => UNDEFINED" )
  set ( foo bar )
  set ( bar )
  twx_assert_non_void ( foo bar )
  twx_test_simple_fail ()
  twx_test_simple_check ( "foo => UNDEFINED, bar => baz" )
  set ( foo )
  set ( bar baz )
  twx_assert_non_void ( foo bar )
  twx_test_simple_fail ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: 0
twx_test_unit_push ( CORE 0 )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "Empty" )
  twx_assert_0 ( "" )
  twx_test_simple_fail ()
  twx_test_simple_check ( "0" )
  twx_assert_0 ( "0" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "Empty, 0" )
  twx_assert_0 ( "" "0" )
  twx_test_simple_fail ()
  twx_test_simple_check ( "0, 0" )
  twx_assert_0 ( "0" "0" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "0, Empty" )
  twx_assert_0 ( "0" "" )
  twx_test_simple_fail ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: true/false
twx_test_unit_push ( CORE "true/false" )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  set ( foo ON )
  twx_test_simple_check ( "foo => ON, TRUE" )
  twx_assert_true ( "foo" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "foo => ON, TRUE, $" )
  twx_assert_true ( "${foo}" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "foo => ON, FALSE" )
  twx_assert_false ( "foo" )
  twx_test_simple_fail ()
  twx_test_simple_check ( "foo => ON, FALSE, $" )
  twx_assert_false ( "${foo}" )
  twx_test_simple_fail ()

  set ( foo OFF )
  twx_test_simple_check ( "foo => OFF, FALSE" )
  twx_assert_false ( "foo" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "foo => OFF, FALSE, $" )
  twx_assert_false ( "${foo}" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "foo => OFF, TRUE" )
  twx_assert_true ( "foo" )
  twx_test_simple_fail ()
  twx_test_simple_check ( "foo => OFF, TRUE, $" )
  twx_assert_true ( "${foo}" )
  twx_test_simple_fail ()

  set ( foo "ON" )
  twx_test_simple_check ( "foo => ON" )
  twx_assert_true ( foo "${foo}" )
  twx_test_simple_pass ()

  set ( foo ON )
  set ( bar ON )
  twx_test_simple_check ( "foo => ON, bar => ON" )
  twx_assert_true ( "${foo}" )
  twx_test_simple_pass ()
  twx_assert_true ( "foo" "bar" "${foo}" "${bar}" )
  twx_test_simple_check ( "foo => ON, bar => ON(2)" )
  twx_assert_true ( "foo" "bar" "${foo}" "${bar}" )
  twx_test_simple_pass ()
  
  twx_test_simple_check ( "foo => UNDEFINED" )
  set ( foo )
  twx_assert_false ( foo "foo" )
  twx_test_simple_pass ()

  twx_test_simple_check ( "Empty" )
  twx_assert_true ( "" )
  twx_test_simple_pass ()

  twx_test_simple_check ( "wizz => UNDEFINED")
  set ( wizz )
  twx_assert_false ( "wizz" )
  twx_test_simple_pass ()

  twx_test_simple_check ( "wizz => UNDEFINED, foo => wizz")
  set ( wizz )
  set ( foo "wizz" )
  twx_assert_true ( "foo" )
  twx_test_simple_pass ()

  twx_test_simple_check ( "foo => N, FALSE" )
  set ( foo N )
  twx_assert_false ( foo )
  twx_test_simple_pass ()
  
  twx_test_simple_check ( "foo => N, TRUE" )
  set ( foo N )
  twx_assert_true ( foo )
  twx_test_simple_fail ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: exists
twx_test_unit_push ( CORE "exists" )
if ( /TWX/TEST/UNIT.RUN )
  block ()
  twx_test_simple_check ( "exists" )
  twx_assert_exists ( "${CMAKE_CURRENT_LIST_DIR}/" )
  twx_test_simple_pass ()
  twx_test_simple_check ( "!exists" )
  twx_assert_exists ( "${CMAKE_CURRENT_LIST_DIR}/NO_FILE_AT_THIS_PATH" )
  twx_test_simple_fail ()
  endblock ()
endif ()
twx_test_unit_pop ()

# ANCHOR: target
twx_test_unit_push ( CORE "target" )
if ( /TWX/TEST/UNIT.RUN AND NOT TARGET TwxAssertTest.cmakeDummyTarget )
  block ()
  twx_test_simple_check ( "No target" )
  twx_assert_target ( "TwxAssertTest.cmakeDummyTarget" )
  twx_test_simple_fail ()
  add_custom_target ( "TwxAssertTest.cmakeDummyTarget" )
  twx_test_simple_check ( "Target" )
  twx_assert_target ( "TwxAssertTest.cmakeDummyTarget" )
  twx_test_simple_pass ()
  endblock ()
endif ()
twx_test_unit_pop ()

endblock ()
twx_test_suite_pop ()

#*/
